# Generated by Django 6.0.6 on 2026-07-13 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReformaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('categoria', models.CharField(max_length=100)),
                ('custo_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('planejamento', 'Planejamento'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='planejamento', max_length=20)),
                ('prioridade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('data_estimavel', models.DateField()),
            ],
        ),
    ]
