# Generated by Django 6.0.6 on 2026-07-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reformaitem',
            name='custo_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
